remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: Tongxin's blog
description: Something here

show_downloads: "true"
# google_analytics: [Your Google Analytics tracking ID]
